'use client'

import { Amplify } from 'aws-amplify'
import { Authenticator } from '@aws-amplify/ui-react'
import { GameProvider } from '@/contexts/GameContext'
import '@aws-amplify/ui-react/styles.css'

// Try to import amplify_outputs.json if it exists (generated by backend deployment)
let amplifyConfig: any

try {
  // This will be generated when the backend is deployed
  amplifyConfig = require('../../amplify_outputs.json')
} catch (error) {
  // Fallback configuration for frontend-only deployment
  console.log('amplify_outputs.json not found, using fallback config')
  amplifyConfig = {
    Auth: {
      Cognito: {
        userPoolId: process.env.NEXT_PUBLIC_USER_POOL_ID || 'us-west-2_placeholder',
        userPoolClientId: process.env.NEXT_PUBLIC_USER_POOL_CLIENT_ID || 'placeholder',
        region: process.env.NEXT_PUBLIC_AWS_REGION || 'us-west-2',
      }
    }
  }
}

// Configure Amplify with either real backend config or fallback
Amplify.configure(amplifyConfig)

export function Providers({ children }: { children: React.ReactNode }) {
  return (
    <Authenticator.Provider>
      <GameProvider>
        {children}
      </GameProvider>
    </Authenticator.Provider>
  )
}
